server:
  port: ${PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        search:
          backend:
            directory:
              type: local-heap
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:fooda}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
      roles: ${SPRING_SECURITY_ROLES}

  application:
    name: fooda-backend-order

  jackson:
    serialization.indent_output: true
    default-property-inclusion: non_null
